name: CarpetPlugin
version: @version@
main: com.ishland.bukkit.carpetplugin.CarpetPlugin
api-version: "1.16"
authors: [ishland]
description: Partital implementation of Carpet Mod
depend: [CommandAPI]
commands:
  player: {}
permissions:
  carpet.player:
    description: "Access to player command"
    default: true
    children:
      - "carpet.player.spawn"
      - "carpet.player.kill"
  carpet.player.spawn:
    description: "Allow spawning fake players"
  carpet.player.spawn.whitelist:
    description: "Allow spawning fake whitelisted players"
    default: false
  carpet.player.kill:
    description: "Allow killing fake players"
